version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "eriri"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    reviewers:
      - "kumavale"
  - package-ecosystem: "cargo"
    directory: "utaha"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
    reviewers:
      - "kumavale"
