version: '3.7'

x-environment: &environment
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST: db
    POSTGRES_PORT: 5432
    POSTGRES_DATABASE: letterpairs

services:
    app:
        build:
            context: .
        environment: *environment
        ports:
            - 8080:80
        networks:
            - letterpairs_net
        volumes:
            - image_volume:/img
        depends_on:
            - db

    db:
        image: postgres:14
        environment: *environment
        ports:
            - 5432:5432
        networks:
            - letterpairs_net
        volumes:
            - postgres_volume:/var/lib/postgresql/data
            - ./sql:/docker-entrypoint-initdb.d

networks:
    letterpairs_net:
        driver: bridge

volumes:
    image_volume:
        driver: local
    postgres_volume:
