version: "3.9"

services:
    frontend:
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        volumes:
            - ./frontend:/app/frontend
        networks:
            - network_llp
        ports:
            - "8080:8080"

networks:
    network_llp:
        driver: bridge
