version: "3.9"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file:
            - ./.env
        environment:
            - MYSQL_HOST=mysql
        networks:
            - network_llp
        ports:
            - "3000:3000"
        depends_on:
            - mysql
    frontend:
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        volumes:
            - ./frontend:/app/frontend
        networks:
            - network_llp
        ports:
            - "8080:8080"
    mysql:
        image: mysql:latest
        platform: linux/amd64
        container_name: mysql_llp
        ports:
            - "3306:3306"
        env_file:
            - ./.env
        volumes:
            - mysql_llp:/var/lib/mysql
        networks:
            - network_llp
    gcs:
        image: fsouza/fake-gcs-server:latest
        container_name: fake-gcs-server
        ports:
            - "4443:4443"
        volumes:
            - ./tests/data:/data
        networks:
            - network_llp
        command: ["-scheme", "http"]

volumes:
    mysql_llp:

networks:
    network_llp:
        driver: bridge
